# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a985b80cc04ea4511112283cec8a6db4ef93b6c7dd916e294051b158a7ba323a6b9e33748e285c3b911088c29619499daf5aad9b85b2a3bfff7025cd38247d5

test:
  secret_key_base: 2aff9fe329f3047b382b274cd3b56eccdafda717227a75a2259cfa5fb4e71ebda6bb516a0730e47c3c37fc820002387782979f285f60370dfb618cf3fa169cf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
